export const GET_UPCOMING_VIDEOS = 'GET_UPCOMING_VIDEOS';
export const GET_POPULAR_VIDEOS = 'GET_POPULAR_VIDEOS';
export const GET_NOW_PLAYING_VIDEOS = 'GET_NOW_PLAYING_VIDEOS';
export const GET_TOP_RATED_VIDEOS = 'GET_TOP_RATED_VIDEOS';
