export const GET_UPCOMING_VIDEOS = 'GET_UPCOMING_VIDEOS';
export const GET_POPULAR_VIDEOS = 'GET_POPULAR_VIDEOS';
export const GET_NOW_PLAYING_VIDEOS = 'GET_NOW_PLAYING_VIDEOS';
export const GET_TOP_RATED_VIDEOS = 'GET_TOP_RATED_VIDEOS';
export const GET_SINGLE_VIDEO = 'GET_SINGLE_VIDEO';
export const GET_VIDEO_PLAYER = 'GET_VIDEO_PLAYER';
export const GET_SIMILAR_VIDEOS = 'GET_SIMILAR_VIDEOS';
export const GET_RECOMMENDATION_VIDEOS = 'GET_RECOMMENDATION_VIDEOS';

export const GET_ERROR_VIDEO = 'GET_ERROR_VIDEO';
export const CLEAR_VIDEO_ERROR = 'CLEAR_VIDEO_ERROR';
